### ISSUE TITLE
Page preview - not renderized

### ISSUE THREAD

**Issue by marlluslustosa** [danurbanowicz/jekyll-netlify-boilerplate#14]
First, great job!
When creating or editing a post, the toggle preview page does not show the rendered content.
Here are some prints.
![Screenshot_20200609_130811](https://user-images.githubusercontent.com/29416568/84173658-fb19c900-aa53-11ea-9506-c3698dcca92f.png)

I don't know if it is relevant information, but, when I clicked the Toogle preview button, I checked an information that appeared in my browser devtools.
![Screenshot_20200609_132048](https://user-images.githubusercontent.com/29416568/84173891-4338eb80-aa54-11ea-942f-5700af4a1aaa.png)

I tested using a private gitlab repository and a public repository on github, deploying with netlify.

**Comment by danurbanowicz** [comment]
Hi! Preview templates could be added in order to show rendered previews but due to time constraints I have no plans to do this currently.

This feature does exist in my [Eleventy starter project](https://github.com/danurbanowicz/eleventy-netlify-boilerplate/) so if you want you can see how it's been implemented [over there](https://github.com/danurbanowicz/eleventy-netlify-boilerplate/tree/master/admin/preview-templates). If you feel like submitting a PR, it could be a nice addition to this project.

The document.write() warning might be caused by `jekyll-watch` if you are running Jekyll locally, although I'm not 100% sure. If you provide more info I can try to reproduce.

**Comment by marlluslustosa** [comment]
Thanks!
Some parameters are missing (date variables), but I tested the CSS and blocks of markdown code and it seems to be working. I opened a [PR](https://github.com/danurbanowicz/jekyll-netlify-boilerplate/pull/15) for testing.
